// <auto-generated />
namespace SurveyTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class init22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init22));
        
        string IMigrationMetadata.Id
        {
            get { return "202005241956227_init22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
