// <auto-generated />
namespace SurveyTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Surveytestv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Surveytestv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261819008_Surveytest-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
